dependabot-bundler 0.158.0
clearlydefined/curated-data pull request #19142
Opened 2022-04-18 18:42 UTC by clearlydefinedbot

**Type:** Missing

**Summary:**
dependabot-bundler 0.158.0

**Details:**
Add NONE License

**Resolution:**
License Url: 
https://github.com/dependabot/dependabot-core/blob/main/LICENSE

Description:
The Prosperity Public License 2.0.0 - defined in source code "LICENSE" file.

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [dependabot-bundler 0.158.0](https://clearlydefined.io/definitions/gem/rubygems/-/dependabot-bundler/0.158.0)

2022-04-18 19:10 UTC, SethStalley requested changes

2022-04-18 19:10 UTC, SethStalley commented on curations/gem/rubygems/-/dependabot-bundler.yaml
> +      declared: NONE
```suggestion
      declared: OTHER
```

2022-04-19 16:19 UTC, capfei commented on curations/gem/rubygems/-/dependabot-bundler.yaml
> +      declared: NONE
@SethStalley Thank you!

2022-04-19 16:19 UTC, capfei approved these changes

2022-04-19 16:20 UTC, merged