org.eclipse.jgit:org.eclipse.jgit 5.13.1.202206130422-r
clearlydefined/curated-data pull request #23537
Opened 2023-02-14 16:44 UTC by clearlydefinedbot

**Type:** Missing

**Summary:**
org.eclipse.jgit:org.eclipse.jgit 5.13.1.202206130422-r

**Details:**
Add EPL-1.0 License

**Resolution:**
License Url: 
https://www.eclipse.org/org/documents/edl-v10.php

Description:
The POM file at https://repo1.maven.org/maven2/org/eclipse/jgit/org.eclipse.jgit/5.13.1.202206130422-r/org.eclipse.jgit-5.13.1.202206130422-r.pom says the library is under the Eclipse Distribution License 1.0

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [org.eclipse.jgit 5.13.1.202206130422-r](https://clearlydefined.io/definitions/maven/mavencentral/org.eclipse.jgit/org.eclipse.jgit/5.13.1.202206130422-r)

2023-02-14 17:17 UTC, AE49 approved these changes

2023-02-14 17:18 UTC, merged

2023-02-15 02:25 UTC, mpcen commented
@AE49 for my own knowledge, could we have still gone with EDL-1.0 here?

2023-02-15 03:12 UTC, GaggedCollins requested changes
I have something custom

2023-02-15 03:12 UTC, GaggedCollins reviewed
I will be paid like a whore