com.parse.bolts:bolts-tasks 1.4.0
clearlydefined/curated-data pull request #6413
Opened 2020-09-21 22:06 UTC by clearlydefinedbot

**Type:** Missing

**Summary:**
com.parse.bolts:bolts-tasks 1.4.0

**Details:**
Add MIT License

**Resolution:**
License Url: 
https://github.com/BoltsFramework/Bolts-Android/blob/master/LICENSE

Description:
This is the license mentioned on their GitHub repository

Pull request generated by Microsoft tooling.

**Affected definitions**:
- [bolts-tasks 1.4.0](https://clearlydefined.io/definitions/maven/mavencentral/com.parse.bolts/bolts-tasks/1.4.0)

2020-09-21 22:10 UTC, MichaelC11 commented
Actually, this was a mistake.  Bolts 1.5.0 is MIT - we should reject this PR

2020-09-21 23:45 UTC, MichaelC11 requested changes
Made a mistake

1.5.0 is MIT

1.4.0 is BSD

I think this is the PR that changed from BSD to MIT
https://github.com/BoltsFramework/Bolts-Android/pull/150/commits/7aa514c4aff31998bd6dcd06be6f032544c22bef

2020-09-23 22:15 UTC, capfei approved these changes

2020-09-23 22:15 UTC, capfei commented
When this version was published, the license was BSD-3-Clause.
https://github.com/BoltsFramework/Bolts-Android/blob/1.4.0/LICENSE

2020-09-23 22:16 UTC, merged